html:
  - '**/*.html'
  - '**/*.htm'

css:
  - '**/*.css'
  - '**/*.scss'
  - '**/*.sass'
  - '**/*.less'

javascript:
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.mjs'

"область: сайт":
  - '**/*.html'
  - '**/*.css'
  - '**/*.js'
  - 'image/**/*'
  - 'json/**/*'
  - 'CNAME'

"область: железо":
  - 'M5stack/**/*'

"область: модули":
  - 'M5stack/**/*'

"область: arduino":
  - 'arduino/**/*'

"область: micropython":
  - 'micropython/**/*'

"область: uiflow":
  - 'uiflow/**/*'

"область: софт":
  - 'soft/**/*'

документация:
  - '**/*.md'

перевод:
  - '**/i18n/**/*'
  - '**/locales/**/*'
  - '**/*.ru.md'
  - '**/*.en.md'
  - '**/*.cn.md'
